name: Release Packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_generic
          - x86_64
          - arm_cortex-a5_vfpv4
        release:
          - openwrt-23.05

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: morytyann/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          FEEDNAME: mihomo
          PACKAGES: luci-app-mihomo
          NO_REFRESH_CHECK: true
          MAKE_ARGS: LUCI_APP_MIHOMO_PKG_VERSION=${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/packages/${{ matrix.arch }}/mihomo/*.ipk
